## Base Image for Streamlit 
FROM python:3.10-slim

## Set working directory
WORKDIR /app_streamlit

## Copy requirements file
COPY requirements.txt .

## Install Dependencies
RUN pip install --no-cache-dir -r requirements.txt

##Copy all projects file
COPY . .

## Expose Streamlit ports
EXPOSE 8501

# Run Streamlit 
CMD ["streamlit", "run", "MainNew.py", "--server.address=0.0.0.0"]